// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snobnrnjzudifcowbshc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNub2Jucm5qenVkaWZjb3dic2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODEyNjksImV4cCI6MjA2MjM1NzI2OX0.52YNF4frhpPugjeNBoObJ3xr-FmFIhR1DIBYd8WmCfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);